#!/bin/bash

# 打印 info
make info

# 主配置名称
PROFILE="generic"

PACKAGES=""

# Argon 主题
PACKAGES="$PACKAGES luci-theme-argon luci-i18n-argon-config-zh-cn"

# System
PACKAGES="$PACKAGES luci-base luci-i18n-base-zh-cn luci-i18n-advanced-reboot-zh-cn luci-i18n-autoreboot-zh-cn luci-i18n-attendedsysupgrade-zh-cn luci-i18n-ttyd-zh-cn luci-i18n-filebrowser-zh-cn luci-i18n-filemanager-zh-cn"

# Proxy
PACKAGES="$PACKAGES luci-app-openclash luci-i18n-homeproxy-zh-cn"

# Network
PACKAGES="$PACKAGES luci-i18n-ddns-zh-cn rsync openssh-sftp-server tailscale etherwake zerotier luci-i18n-zerotier-zh-cn"

# Utilities
PACKAGES="$PACKAGES unzip sshpass luci-i18n-upnp-zh-cn  luci-i18n-lucky-zh-cn"

# 一些自定义文件
FILES="files"

# 禁用服务
DISABLED_SERVICES=""

make image PROFILE="$PROFILE" PACKAGES="$PACKAGES" FILES="$FILES" DISABLED_SERVICES="$DISABLED_SERVICES"
